### ISSUE TITLE
[REQUEST] Different pin code for app than the lockscreen

### ISSUE THREAD

**Issue by newstart** [Cyl18/OnePlus-5T-Applock-Tweaker#3]
Assume I want to give my phone to my kids who know my lockscreen pin. If I want to use this module to block access to certain apps, I cannot since it uses the device pin instead of a unique pin.

May this be changed in a future update?

**Comment by Cyl18** [comment]
done, you can download it from GitHub release or Xposed repo http://repo.xposed.info/module/com.cyl18.opapplocktweaker
:)

**Comment by newstart** [comment]
You are absolutely amazing!!!! Thank you!!!!
