### ISSUE TITLE
一加5能不能用啊

### ISSUE THREAD

**Issue by loneyyao** [Cyl18/OnePlus-5T-Applock-Tweaker#4]
一加5装上发现不能用,不知道人脸识别在哪里启用,
现在只能用的功能是修改app锁的密码与开机密码不一样

**Comment by Cyl18** [comment]
人脸识别是系统的 根据评论区的反馈 好像要升级到系统最新

**Comment by LasmGratel** [comment]
According to OnePlus forum, currently versions released after OxygenOS Open Beta 3 would be able to use face unlock ability.

Forum link: https://forums.oneplus.net/threads/oxygenos-open-beta-3-android-o-for-the-oneplus-5.732933/

Please ensure that you have just upgraded to the latest version.
